services:
  db:
    image: postgres:16-alpine
    container_name: rapid-logistics-postgres-container-2
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

#  # ==========================================================
#  # 2. BACKEND (Spring Boot)
#  # ==========================================================
  backend:
    # GHCR Putanja: mislavcupic/rapid-java-project/ime_slike:tag
    image: ghcr.io/btn3/rapid-java-project/backend:latest
    container_name: logistics-backend
    restart: always
    ports:
      - "8080:8080"
    environment:
#      # Konekcija na DB servis (koristi ime servisa 'db')
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
#      # OmoguÄ‡ava /actuator/prometheus endpoint za monitoring (LO9)
      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: health,info,prometheus
    depends_on:
      - db
#
#  # ==========================================================
#  # 3. FRONTEND (React/Nginx)
#  # ==========================================================
  frontend:
#    # GHCR Putanja: mislavcupic/rapid-java-project/ime_slike:tag
    image: ghcr.io/mislavcupic/rapid-java-project/frontend:latest
    container_name: logistics-frontend
    restart: always
    ports:
      - "5173:5173"
    environment:
#      # Konekcija na Backend servis (koristi ime servisa 'backend')
      REACT_APP_API_URL: http://backend:8080
    depends_on:
      - backend
