services:
  db:
    image: postgres:16-alpine
    container_name: rapid-logistics-postgres-container-2
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
#komentar
#  # 2. BACKEND (Spring Boot)

  backend:
    # GHCR Putanja: mislavcupic/rapid-java-project/ime_slike:tag
    image: ghcr.io/btn3/rapid-java-project/backend:${IMAGE_TAG:-latest}
    container_name: logistics-backend
    restart: always
    ports:
      - "8080:8080"
    environment:
#      # Konekcija na DB servis (koristi ime servisa 'db')
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/logistics_fleet_v2
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
#      # OmoguÄ‡ava /actuator/prometheus endpoint za monitoring (LO9)
      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: health,info,prometheus
    depends_on:
      - db
#
#  # ==========================================================
#  # 3. FRONTEND (React/Nginx)
#  # ==========================================================
  frontend:
## GHCR Putanja: mislavcupic/rapid-java-project/ime_slike:tag
    image: ghcr.io/btn3/rapid-java-project/frontend:${IMAGE_TAG:-latest}
    container_name: logistics-frontend
    restart: always
    ports:
      - "5173:80"
    environment:
## Konekcija na Backend servis (koristi ime servisa 'backend')
      VITE_API_URL: http://backend:8080
    depends_on:
      - backend


  # ==========================================================
  # 4. PROMETHEUS (Monitoring - LO9)
  # ==========================================================
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    depends_on:
      - backend

#  # ==========================================================
#  # 5. GRAFANA (Vizualizacija - LO9)
#  # ==========================================================
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: ${GF_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GF_PASSWORD}
    depends_on:
      - prometheus
volumes:
  postgres_data:
